# config/secrets.yaml
# --------------------
camera:
  rtsp_url: "rtsp://admin:Victoria2313*@192.168.100.229:554/stream1"

live:
  auth_token: "null"

api:
  endpoint_url: "http://192.168.100.14:5086/api/AiDetection/PlateDetected"
